### ISSUE TITLE
Server can't find serial node on boot when uart3 is enabled on Pi 5

### ISSUE THREAD

**Issue by SpencerGraffunder** [RotorHazard/RotorHazard#907] opened 2024-05-17 13:57 UTC
**Confirm the issue is with RotorHazard and not a plugin**
The problem happens whether I have plugins installed or not, but the reason this is significant is that the Pi 5 needs UART3 enabled to use VRxC plugin on NuclearHazard boards.

**Describe the bug**
When the following conditions are met:
- Using Pi 5 and an STM32 node
- Have dtoverlay=uart3-pi5 in config.txt
- Server has started for the first time since boot

The server does not recognize the STM32 node.

In this state, if either of the following are done, the server recognizes the STM32 node:
- Restart the server (eg. sudo systemctl restart rotorhazard)
- Flash the STM32 through the UI

**To Reproduce**
1. Have RotorHazard running normally on a Pi 5 (experienced on 4.1.0 beta 4 and 5)
2. Add dtoverlay=uart3-pi5 to an appropriate section of /boot/firmware/config.txt
3. Reboot the Pi (and manually start server if not started automatically)

**Expected behavior**
The server will find the STM32 as a node and show receivers.

**Log Dump**
[withuart3afterserverrestart.zip](https://github.com/RotorHazard/RotorHazard/files/15350368/withuart3afterserverrestart.zip)
Log 083655 is from the boot before the dtoverlay is added, so the problem is not present there, but this log can be used as the control.
Log 084201 is from after the dtoverlay is added and the Pi is rebooted. The message `Unable to initialize serial node(s): ['/dev/ttyAMA0']` is unexpected.
Log 084602 is on the same boot but the server was just restarted, and the STM32 is recognized `Serial multi-node found at port '/dev/ttyAMA0', count=2, API_level=35, baudrate=921600, fw_version=1.1.5, fw_type=STM32F1, fw_timestamp: Jan 17 2024 17:23:23`.

**Comment by ethomas997** [comment] 2024-05-19 04:55
@SpencerGraffunder I am not able to reproduce the problem.  I see that in all the logs there is a plugin installed.  If you're seeing it happen without the plugin installed, a good next step would be to start with a new/full install of the Pi OS and RotorHazard onto a new SD card, see if the issue shows up on there, and then post a download-logs '.zip' file from that setup.

**Comment by Flight** [comment] 2024-06-05 12:41
Confirm with the 4.1.0 release. Using RotoHazard 5 board + raspberry pi 5 4gb.

**Comment by SpencerGraffunder** [comment] 2024-06-08 14:49
I just replicated this on a fresh OS install by following the Software Setup.md instructions exactly other than the username (changed in all necessary places) and I added uart3-pi5 to the config.txt. It still exhibits the same behavior. No plugins. There's no "reopen" button here for me, so maybe you'll have to reopen it, @ethomas997.

**Comment by SpencerGraffunder** [comment] 2024-06-09 12:24
I was just testing a timer without a backpack, so without uart3 enabled, and it’s having the same problem now too.

**Comment by ethomas997** [comment] 2024-06-10 06:11
@SpencerGraffunder Thanks for followup info.  I was able to reproduce the issue when using the very-latest Pi OS "Debian GNU/Linux 12 (bookworm) 64-bit (Linux 6.6.31+rpt-rpi-2712)" and adding "dtoverlay=uart3-pi5" to the boot 'config.txt' file.  I've posted a [commit](https://github.com/RotorHazard/RotorHazard/commit/a759846b12011a394422af9c00b1b89423a3dd70) that should fix this issue.

**Comment by ethomas997** [comment] 2024-06-10 18:18
@SpencerGraffunder I'm closing this issue as completed; let me know if you still see the problem in future.

**Closed by ethomas997** 2024-06-10 18:18 UTC
