### ISSUE TITLE
Different channels for heats, or option to split a 8 channel timer so you could select 1-4 or 4-8 per heat.

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#596] opened 2021-05-29 20:05 UTC
Running a race I found that some pilots was on DJI and others was on analog, I split the dji pilots so they were together and analog where with analog pilots to reduce any issues. My issue there is no way of changing or setting channels and there tuning for different heats. This ment the DJI pilots did not get any practice times as I could not include them.

My solution if possible is to give an ability to change the channels for each heat if needed including tuning.

The only other way would be to split 8 way in to 4 so one heat could run 1-4 channels analog for heat and another could run the remaining 4-8 as digital for another heat if this was split it would be nice to have split IMD rating for this.

**Comment by BoLtWD** [comment] 2021-05-30 21:58
One problem another problem I have found using Shark Shark Byte.
If someone was using Fat Shark Shark Byte on 5695 I have found that the tuning has to be set lower for this than analog. 
This means you could not use this same channel for analog as this would not pick up without re-tuning, if there are no other pilots on Shark Byte you have lost this channel for for any other heats. 

The best option would to be-able to have selectable channels for each heat and tuning assigned to each channel used for a specific node.

**Comment by HazardCreative** [comment] 2021-05-30 23:32
> My issue there is no way of changing or setting channels and there tuning for different heats.

Switch profiles.
 
> My solution if possible is to give an ability to change the channels for each heat if needed including tuning.

Duplicate of #391

> The only other way would be to split 8 way in to 4 so one heat could run 1-4 channels analog for heat and another could run the remaining 4-8 as digital for another heat

No issues there.

> if this was split it would be nice to have split IMD rating for this.

IMD is only needed when setting up your channel set, and doesn't affect spread-spectrum (DJI digital) nearly as much. Just check the analog half IMD before adding your DJI channels.

> If someone was using FS Shark Byte on 5695 or other I have found that the tuning has to be set lower for this than analog.
> This means you could not use this same channel for analog as this would not pick up without re-tuning, if there are no other pilots on Shark Byte you have lost this channel for for any other heats.

Adaptive calibration resolves this, in the same way that it will if you have a pilot on a weak analog VTx.

**Closed by HazardCreative** 2021-05-30 23:32 UTC
Labels: duplicate, enhancement
