### ISSUE TITLE
Reload race data after commit changes when marshaling

### ISSUE THREAD

**Issue by DavidJJ** [RotorHazard/RotorHazard#240] opened 2020-02-08 19:06 UTC
Version: 2.1 Beta.

If you recalc and adjust a race on the marshal page, commit changes,  go to another pilot, then back to first pilot  Rotorhazard shows you the data from before you redid the race. 

If you reload the page the saved results will be shown, but not if you jump to a different race and then back.

**Comment by HazardCreative** [comment] 2020-02-08 19:18
Thanks for the report! This one has actually already been taken care of in the latest code, it's just not in a published release yet.
Duplicate of #142 and fixed by c54474f.

**Closed by HazardCreative** 2020-02-08 19:18 UTC
Labels: duplicate
