### ISSUE TITLE
Announce "Pilot Done"

### ISSUE THREAD

**Issue by Footr** [RotorHazard/RotorHazard#575] opened 2021-05-02 02:50 UTC
When the race time ends and the pilot completes their final lap along with the final time the announcer should announce "Pilot done".

**Comment by Aaronsss** [comment] 2021-05-02 20:20
This is a duplicate of #500 and #501 

I too am very much looking forwards to this feature being implemented

**Comment by skyfpv** [comment] 2022-04-30 07:59
I've found this to be a much needed feature as well. Had to have a couple tough conversations with pilots when they thought they beat the timer, or worse: landed too early.

**Closed** 2022-09-29 00:19 UTC
Labels: enhancement
