### ISSUE TITLE
server crash on first boot

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#552] opened 2021-04-09 22:04 UTC
I am trying to run the released beta on a raspberry pi zero and I get the following error where it looks like it can't create the initial database?

RotorHazard v3.0.0-beta.1
Release: 3.0.0-beta.1 / Server API: 30 / Latest Node API: 34
Host machine: Raspberry Pi Zero W Rev 1.1
Host OS: Linux 5.10.17+
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)
Host machine is 'Laptimer2' at 192.168.1.121
No configuration file found, using defaults
Using log file: logs/rh_20210409_230115.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...No I2C node at address 8
...No I2C node at address 10
...No I2C node at address 12
...No I2C node at address 14
...No I2C node at address 16
...No I2C node at address 18
...No I2C node at address 20
...No I2C node at address 22
*** WARNING: NO RECEIVER NODES FOUND ***
Traceback (most recent call last):
  File "server.py", line 5845, in <module>
    db_init()
  File "server.py", line 4828, in db_init
    DB.create_all() # Creates tables from database classes/models
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 962, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py
", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
Loaded module ina219_sensor
Loaded module linux_sensor
Core temperature available
No 'database.db' file found; creating initial database
pi@Laptimer2:~/RotorHazard/src/server $

**Comment by HazardCreative** [comment] 2021-04-10 04:06
Server started normally on latest 3.0 branch, Windows 10, Python 3.8.5 with no database file present.

**Comment by Aaronsss** [comment] 2021-04-10 16:13
I just re tried from scratch the steps taken were as follows:
Install Raspberry Pi OS Lite (Release date: March 4th 2021) to a 64GB card
Login and enable wifi, SSH and change password
I then followed the SoftwareSetup page exactly via SSH down to the manual start section, omitting all optional parts

I get the same error as above, if I try running as root it makes no difference

If I install a database file from my other timer I get this error instead:

```
RotorHazard v3.0.0-beta.1
Release: 3.0.0-beta.1 / Server API: 30 / Latest Node API: 34
Host machine: Raspberry Pi Zero W Rev 1.1
Host OS: Linux 5.10.17+
Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)
Host machine is 'LapTimer2' at 192.168.1.121
No configuration file found, using defaults
Using log file: logs/rh_20210410_170402.log
Loaded module i2c_helper
Loaded module i2c_node
Loaded module serial_node
Searching for I2C nodes...
...No I2C node at address 8
...No I2C node at address 10
...No I2C node at address 12
...No I2C node at address 14
...No I2C node at address 16
...No I2C node at address 18
...No I2C node at address 20
...No I2C node at address 22
*** WARNING: NO RECEIVER NODES FOUND ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0xb61cdea0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 5858, in <module>
    Options.primeGlobalsCache()
  File "/home/pi/RotorHazard/src/server/Options.py", line 11, in primeGlobalsCache
    settings = Database.GlobalSettings.query.all()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/scoping.py", line 129, in __call__
    return self.registry()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 4044, in __call__
    return self.class_(**local_kw)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 943, in engine
    return self.get_engine()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.7/dist-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
Loaded module linux_sensor
Core temperature available
```

Could it be because I have no nodes attached?

**Comment by HazardCreative** [comment] 2021-04-11 22:21
Thanks for the update. We'll continue trying to reproduce a bit more as my previous test wasn't on similar hardware.

**Comment by ethomas997** [comment] 2021-04-12 20:34
I got a Pi Zero W setup and am able to reproduce that error.  I'll post when I have a fix.

**Comment by ethomas997** [comment] 2021-04-13 05:12
Looks like the issue here is similar to #535.  The next beta release will include a fix for this, but in the meantime you should be able to get your server running via this command:

`sudo pip install SQLAlchemy==1.3.*`

**Comment by Aaronsss** [comment] 2021-04-13 22:15
I can confirm the above worked. (Until I blew up the pis WiFi chip :( )

**Closed** 2021-04-14 20:27 UTC
Labels: bug
