### ISSUE TITLE
Error when starting the server on the Linux WSL without the nodes

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#255] opened 2020-03-02 23:05 UTC
I cannot run server on a PC without nodes connected. Occurs on PC with Linux Mint installed and WSL - Ubuntu. Update: On Windows works with no problem. 
Error as on image attached.
![22DC6C94-C4B4-4A15-9D1C-4B2BECA4327D](https://user-images.githubusercontent.com/23621888/75726429-b0651400-5ce2-11ea-8975-3b77d333175d.jpeg)

**Comment by ethomas997** [comment] 2020-03-05 00:19
Commit https://github.com/RotorHazard/RotorHazard/commit/2e8314f4460e684337d11f23e4de2e63382eeb54 should fix; please test.

**Comment by szafranski** [comment] 2020-03-05 01:27
Tested:
![image](https://user-images.githubusercontent.com/23621888/75938741-d1676980-5e88-11ea-9c8e-452c2b6d3e8a.png)

**Comment by pulquero** [comment] 2020-03-05 01:31
That wont really fix anything. The problem is in BaseHardwareInterface and the sensors. There is nothing wrong with MockInterface calling discover_sensors.

**Comment by szafranski** [comment] 2020-03-05 01:32
On Windows still works 100% fine. Error on Linux - this one tested on WSL.

**Comment by ethomas997** [comment] 2020-03-05 02:27
It looks like there are dependencies missing.  Have you installed the RotorHazard server dependencies on the system(s)?  You'll want to run commands like this on linux:
```
cd ~/RotorHazard/src/server
sudo pip install -r requirements.txt
```
If you're still getting errors after that, please put your full RotorHazard directory into a .zip or .tar.gz archive and post it.

**Comment by szafranski** [comment] 2020-03-05 02:54
Thanks for helping me. Dependencies were already satisfied. I am attaching folder than. I tried to copy it to main linux home folder, changing name etc. Still nothing.
[RotorHazard-master (4).zip](https://github.com/RotorHazard/RotorHazard/files/4290696/RotorHazard-master.4.zip)

**Comment by ethomas997** [comment] 2020-03-05 04:23
Hmmm, I don't know.  When I unpack and run your posted fileset on a Linux Mint system it seems to run fine.  That ImportError on your output sure looks like what you'd get if the 'python-socketio' library is not installed/available.

**Comment by szafranski** [comment] 2020-03-05 05:11
I just tried on Linux Mint - yet another installation on another desktop. Now I get this error but only when I am using command like: 
python ~/RotorHazard/src/server/server.py
When I am in folder ~/RotorHazard/src/server already and I than type 
python server.py - it starts.

For me - mega weird... Isn't it?

**Comment by ethomas997** [comment] 2020-03-05 05:57
Running it with "python ~/RotorHazard/src/server/server.py" is incorrect.  It needs to be "cd ~/RotorHazard/src/server" and then "python server.py", as per [docs](https://github.com/RotorHazard/RotorHazard/blob/master/doc/Software%20Setup.md#otheros).

**Comment by szafranski** [comment] 2020-03-05 06:24
Ok, I thought that it should behave the same. Even if in this case we know
what went wrong, it doesn’t explain what went wrong on another laptop and
on wsl - I was trying from same folder...

W dniu czw., 5.03.2020 o 06:57 E Thomas <notifications@github.com>
napisał(a):

**Comment by ethomas997** [comment] 2020-03-05 22:02
Please do these on a (Linux) system that's giving you an 'ImportError' and post the output:
```
python server.py

pip list
```

**Comment by ethomas997** [comment] 2020-03-06 00:38
It may be that the 'socketio' package is interfering with the 'python-socketio' package.  Try uninstalling it with "sudo pip uninstall socketio".  If that doesn't work you may need to uninstall the whole python package and reinstall it.

**Comment by szafranski** [comment] 2020-03-06 00:48
Thanks. Do I have to do anything else? Server doesn't work still.

![image](https://user-images.githubusercontent.com/23621888/76039341-7008ce80-5f4c-11ea-9b42-9cf4d35fe9cc.png)

**Comment by ethomas997** [comment] 2020-03-06 00:57
Try uninstalling/reinstalling python on the system.

**Comment by szafranski** [comment] 2020-03-06 00:59
Is it a good idea to try removing those packages shown on image above and than test once again or just uninstall python? 
What command should I use? just sudo apt remove python* ?

**Comment by HazardCreative** [comment] 2020-03-06 01:14
Is they python version a problem? I don't expect too many new systems will come with Python 2 as it's  officially gone end-of-life now. (We should consider moving away now as well.)

**Comment by ethomas997** [comment] 2020-03-06 02:44
Looks like it was python 2.7, which is the version we want.  For python reinstall, I'd say goggle it with the name of the OS.

**Comment by szafranski** [comment] 2020-03-06 03:11
k, thanks

**Comment by szafranski** [comment] 2020-03-06 09:47
I think I have important hint. Looks like server refuses to start when additional packages like rpi-leds etc are installed. When they don't it starts.

**Comment by szafranski** [comment] 2020-03-06 13:53
Started to work now on Linux laptop. I don't know if you changed something meantime or not.

**Comment by szafranski** [comment] 2020-03-07 04:12
Ok, so tbh I don't know if anyone is still interested in solving this - no offense, just wondering! - but as right now on Linux PC it works but on WSL after flash installation I got this:

Idk how important WSL is for devs too but I like it 100x more than Windows PowerShell or cmd.
![image](https://user-images.githubusercontent.com/23621888/76136470-20043780-6032-11ea-85e3-e418242b9aca.png)

**Comment by ethomas997** [comment] 2020-03-07 08:53
Yes, still interested and please do keep testing; it helps us a lot.  I think my latest commit should help with that IOError issue.

**Comment by HazardCreative** [comment] 2020-03-07 12:01
> I performed and updated and it works.

I thought that this meant you had solved it. It can be reopened if that's not the case.

**Comment by szafranski** [comment] 2020-03-07 16:48
Maybe I used wrong words - twice. Sorry if thats the case. So the situations is like this. It started to work on Linux but on wsl I got this error. Cheers

**Comment by ethomas997** [comment] 2020-03-07 20:58
How is it working now with the current 'master' code?

**Comment by szafranski** [comment] 2020-03-08 03:05
I think we can call it a success! 

"Errno" shows but works :)

![image](https://user-images.githubusercontent.com/23621888/76155821-00344880-60f2-11ea-89d1-593e3dcbec37.png)

**Comment by ethomas997** [comment] 2020-03-08 06:36
Cool.  That error message is fine for the simulated / mock nodes setup.

**Comment by szafranski** [comment] 2020-03-08 07:30
Thanks for diggind deep :)

**Comment by ethomas997** [comment] 2020-03-28 23:42
Closing this issue as resolved; please reopen and comment or post new issue if there's still a problem.

**Closed by ethomas997** 2020-03-28 23:42 UTC
