### ISSUE TITLE
Unable to seed heats via class rank for plugin generated heats

### ISSUE THREAD

**Issue by skyfpv** [RotorHazard/RotorHazard#882] opened 2024-03-25 11:18 UTC
I'm working on a plugin which generates heats for the Street League points format. Some of the heats (stage 2 and beyond) seed pilots based on their class rank. The plugin successfully generates the heats, but when I attempt to seed the heats by class rank using the "seed now" button, no pilots are found for the heat. This bug only appears when the heats are created via plugin. It does not appear when the heats are created via the browser UI.

**branch**
main

**To Reproduce**
1. install the plugin from https://github.com/skyfpv/streetleague_rotorhazard_plugin
2. create a pilot
3. generate heats using the new "Street League Points" generator (2 stages is all that's needed to reproduce this bug, but more can be useful for debugging)
4. run the heat called "Stage 1 - Heat A" and give the pilot a lap or two
5. verify that the pilot is position 1 in the results page
6. in the format page, click "seed now" on "Stage 2 - Heat A"
7. Note that no pilot is found for rank 1 in the class
8. Note that the exact same scenario works fine when set up via the browser UI

**Expected behavior**
The pilot in rank 1 for the class should be seeded into the heat.

**Screenshots**
![image](https://github.com/RotorHazard/RotorHazard/assets/45609851/c76b3a87-2890-4859-82bd-fbd65723aeec)

**Possible Fix**
I believe the issue lies in heat_automation.py (line 153). The function above alters the slot objects, but the db is not successfully committing the changes made to that object (I'm not entirely sure why). However, calling merge(slot) followed by a commit() for each slot appears to resolve the issue.

replace heat_automation.py (line 151)
```
            logger.debug('Slot {} Pilot is {}'.format(slot.id, slot.pilot_id if slot.pilot_id else None))
            self._racecontext.rhdata.merge(slot)
            self._racecontext.rhdata.commit()
        
        return result
```

add merge method in RHData.py (line 114)
```
    def merge(self, obj):
        try:
            Database.DB_session.merge(obj)
            return True
        except Exception as ex:
            logger.error('Error writing to database: ' + str(ex))
            return False
```

**Relevant Dump**
[seed_now_bug.log](https://github.com/RotorHazard/RotorHazard/files/14742571/seed_now_bug.log)

**Comment by HazardCreative** [comment] 2024-04-04 01:31
Are you using a fork?

```
  File "RotorHazard\src\server\plugins\streetleague\__init__.py", line 253, in StreetLeaguePointsGenerator
    seedMethod = SeedMethod.CLASS_ID
...
AttributeError: CLASS_ID
```

**Comment by arnaudmorin** [comment] 2024-04-16 16:31
I have exactly the same behavior, I am using the 3 best laps plugins, but I think it's not related to any plugin. I believe the move to sqlalchemy2 is maybe the root cause.
Sometimes, the db commit() is not committing anything.

It's also visible when you clean cache (under results UI) and take a look at the cache rebuild logs. You'll see that the race results are not committed.

**Comment by HazardCreative** [comment] 2024-04-26 22:36
Closing because the code in question is not in the codebase, but also because [70ab69f](https://github.com/RotorHazard/RotorHazard/commit/70ab69f0f5b055ed0d485e361a043f7f1f314b69) probably fixes it.

Thanks to @i-am-grub for a repro case supplied elsewhere.

**Closed by HazardCreative** 2024-04-26 22:36 UTC

**Comment by skyfpv** [comment] 2024-06-03 18:18
Just wanted to confirm v4.1.0 official seems to have fixed this. Sorry for some of the confusion, and thanks for all the hard work!
