### ISSUE TITLE
Staging beep incorrectly played before race start.

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#448] opened 2020-10-29 11:41 UTC
Running the dev6 version of rotor hazard at last weeks race. (It has none of my previous modifications).

I configure  system such that it will NO staging tones.  No countdown , no random time.  My desire is for the first audible tone for pilots to hear is the start of the race. (This improves throughput, reduces false starts by pilots, and is the mode that MultiGP uses at all big events like IO and championships).

While the new code is greatly improved, it did occur one time where a single staging tone sounded before the main start tone.

Protections should be put in the code to prevent this.  It’s better than it used to be as it only occurred once,  but the fact that it did occur means there still a timing window where it can happen.

**Comment by HazardCreative** [comment] 2020-11-08 15:34
I'd like to know more about the circumstances of this. Is it possible that you loaded the page and tried to kick off a race very quickly, before the page had a chance to collect status from the server? Or can you give me any more information about when and how this occurred?

----

Some reference for devs to help track this down:

The tone playing code only activates if staging_tones is TONES_ONE or TONES_ALL:
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/static/rotorhazard.js#L1003
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/static/rotorhazard.js#L1021-L1022
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/static/rotorhazard.js#L1036-L1037

This tones setting is local to the browser. Tones default to ALL but are updated with the race status. Status is sent by the server when it changes, or requested by the run page on load.
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/templates/run.html#L217
https://github.com/RotorHazard/RotorHazard/blob/master/src/server/templates/run.html#L17

**Comment by HazardCreative** [comment] 2021-02-11 03:13
Unable to reproduce without additional information; closing.

**Closed by HazardCreative** 2021-02-11 03:13 UTC
Labels: bug
