### ISSUE TITLE
Track and log rejected lap passes

### ISSUE THREAD

**Issue by ethomas997** [RotorHazard/RotorHazard#23] opened 2019-01-29 21:38 UTC
Track number of lap passes rejected because time is below min-lap-time (per node)

reset counts at race start
log counts at race stop
Also, stop logging all lap passes

Could also see about saving counts to database.

**Comment by HazardCreative** [comment] 2019-01-29 21:42
Duplicate of #6 with a different approach to resolving?

**Comment by ethomas997** [comment] 2019-01-29 21:49
This is just a quick mod to have the info logged.

**Comment by HazardCreative** [comment] 2019-02-07 21:58
Should ExitAt be raised automatically if the rejected pass count (or any pass count, really) is too frequent?

**Comment by ethomas997** [comment] 2019-02-07 22:11
Wouldn't want the system to be doing automatic adjustments in response to someone just free-flying around.  Really don't want the system doing any automatic adjustments unless we're 100% sure about them.

**Comment by HazardCreative** [comment] 2019-02-08 01:01
On further consideration, I agree. I was thinking that it's obvious something isn't right when the node is flipping more than once in a 5-second window. But we also got some erratic behavior approaching this when micros were sitting in the pits maybe 10ft away from the timer. I wouldn't want that adjusting it.

**Closed** 2019-02-09 23:03 UTC
Labels: enhancement
