### ISSUE TITLE
Not ending the race immediately when one pilot finishes X laps in "First to X Laps" format

### ISSUE THREAD

**Issue by evilmerlin** [RotorHazard/RotorHazard#686] opened 2022-11-22 06:52 UTC
Feature request for new race format.
Currently the First to X Laps format "ends" the race the moment one pilot finishes X laps and the pilots are ranked according to their position as of that time.

**Describe the solution you'd like**
What I would like to see is the race continue until either all pilots have finished the 5 laps or crashed out. Mainly so that even after the winner has finished 5 laps, the other 3 pilots still has to continue racing for position.
For example you have a lead pilot who has finished 5 laps but the other 3 are still on their 4th lap or starting their 5th. Instead of immediately ending the race there and then, the remaining pilots are still allowed to race for a better position.

**Comment by HazardCreative** [comment] 2022-11-22 12:03
> Currently the First to X Laps format "ends" the race the moment one pilot finishes X laps and the pilots are ranked according to their position as of that time.

This is not expected behavior, and I cannot reproduce it. Under what conditions does this occur?

**Comment by evilmerlin** [comment] 2022-11-23 06:38
Sorry, should have been clearer. I don't mean end the race as though I clicked the Stop Race button. The timer still records laps but I had to go the Marshal page to add them back. There were marked as deleted.

It's not a show stopper by any means.

**Comment by HazardCreative** [comment] 2022-11-23 12:27
While the previous beta release did behave this way, it was adjusted for 3.2.0-beta.2. Please ensure you are reviewing the latest beta release. 

If you still experience the behavior, this is a bug—please provide database, log, and reproduction steps.

**Comment by HazardCreative** [comment] 2023-01-28 21:01
Closing issue because no update has been provided. Please re-open with reproduction steps if it re-appears.

**Closed by HazardCreative** 2023-01-28 21:01 UTC
Labels: enhancement
