### ISSUE TITLE
Weird issues with power on the newest Raspbian 11 (Bullseye)

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#633] opened 2021-11-10 12:32 UTC
Raspberry Pi 4 is not willing to boot when powered using GPIO pins (the way we expect users to do it).
It is powering on with no problem when connected using USB-C. To be confirmed by someone else. 

Platform:
Raspberry Pi 4 with Raspbian 11 (Bullseye)

**Comment by ethomas997** [comment] 2021-11-21 07:51
I've tested with an RPi4/Bullseye powered via pins on the 40-pin connector; seems to run fine for me.

**Comment by szafranski** [comment] 2021-11-21 09:26
My Pi boots no problem if powered via GPIO pins when Buster is in use. If SD card (or USB) contains Bullseye, it is not willing to boot. Checked multiple times. But Dave Just seems to do not have any issus - as you. Maybe something very weird is going on on my Pi. Some eeprom-related power issues? Idk, mega-weird but seems that it is not anything that will affect other users, so maybe we should leave that issue opened, so users with that problem had a hint that it happened to others. At least for next month or so, because many people will update their OS I suppose. If you just want to close the issue - no problem for me too. 
|One question - have you tried it with fresh install of Bullseye or after updating from Buster?

**Comment by ethomas997** [comment] 2021-11-21 09:49
I did a fresh install of Bullseye

**Comment by szafranski** [comment] 2021-11-21 09:51
Ok, so same as me. Nothing else to ass from my side then.

**Comment by WombatControl** [comment] 2022-01-03 18:20
I am having the same issue right now - the system refuses to boot up when the GPIO pins are connected, even if power is being applied to USB-C instead. My thought was that enabling I2C through raspi-config might be a fix, but even after powering solely from USB-C with I2C enabled the Pi will not boot from the GPIO pins. This is on a Pi4 running the latest Bullseye ISO.

**Comment by szafranski** [comment] 2022-01-03 18:22
Have you tried with another/previous raspbian?

**Comment by WombatControl** [comment] 2022-01-03 19:22
Yes, the system works just fine with Buster, so there has to be something in Bullseye that causes an issue. It could be limited to just a particular hardware revision of the Pi4 - I will try with another Pi and do some testing to see if that may be the case.

**Comment by ethomas997** [comment] 2022-01-03 19:40
It may be that the Pi with Bullseye is drawing more power during the bootup and it's too much for the power circuit.  I'm not able to reproduce the issue, so I can only really guess.  Is there anything non-standard about your setup?  The 5V power comes from the regulator at U12, so you could try replacing that, and you could try a different ribbon cable.

**Comment by pulquero** [comment] 2022-01-03 20:05
I used to get low power warnings on Buster. I found I was getting something like a 0.2V drop over the power cables. Switching to thicker cables resolved the problem.

**Comment by ethomas997** [comment] 2022-04-17 05:51
Closing this issue; feel free to reopen if needed

**Closed by ethomas997** 2022-04-17 05:51 UTC
