### ISSUE TITLE
All nodes fail to be updated or seen by the PI after running a long time.

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#179] opened 2019-09-15 02:05 UTC
During the last race I did have one 'glitch' where it was not communicating with any of the nodes. The PI was still functioning as the web UI was all appearing to be working. But the rssi values for ALL nodes was just flatline never changing. The lights on the nodes were still blinking. This occurred after running about 2 hours.
I resorted to rebooting the PI and things resumed normally.

**Comment by Cuxx** [comment] 2019-11-12 21:30
I have the issue basically every session that's longer than one hour. But I'm still on V2.0.1. Haven't tried 2.0.2 yet

**Comment by RogerBFPV** [comment] 2019-12-22 01:25
I've used the system now for 4 additional fairly large races, with 15+ pilots for many hours and have not seen this problem since the first time it hit..

**Comment by ethomas997** [comment] 2019-12-22 01:31
I've seen this issue on my timers, intermittently when they've been running for a long time.  My current theory is that one or more nodes can get into an unstable state where they end up trashing the I2C bus.  I plan on looking at implementing a watchdog timer on the nodes that will do a reset if communication to the node stops.

**Comment by RogerBFPV** [comment] 2019-12-22 02:04
What would be the ramifications of this watchdog reset? Could it result in missing laps without the race director knowing about it? 
Could there be some more significant underlying hardware issue that we need to address?

**Comment by ethomas997** [comment] 2019-12-22 02:12
My expectation is that, if the watchdog is triggered (because node comms have stopped), the system will be in a non-operational state already.  What may often happen is that the issue will arise while the timer is idle and the watchdog will fix it.

**Comment by ethomas997** [comment] 2020-01-12 02:52
I tried to setup the Arduino hardware watchdog in the node code, but it turned out the bootloader on the Arduino Nano does not support it, and module ends up in a stuck/frozen state.

However, I did find I could implement an I2C communications monitor in software that resets the bus pins, and this does seem to effectively clear the "stuck" condition, allowing the communications to resume.  So, while there still may be occasional "interface" error messages, the timer should always recover from them.

This fix is in commit https://github.com/RotorHazard/RotorHazard/commit/2c11e4fececa114306eb17b00007342030a62de5, and will be in the next beta release.  (Closing this issue; please reopen or file a new issue if it looks like the problem is not fixed.)

**Closed by ethomas997** 2020-01-12 02:52 UTC
