### ISSUE TITLE
New issue on main - only when connected to NH PCB

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#855] opened 2024-02-02 00:44 UTC
Hi, just got this on the fresh install:

![image](https://github.com/RotorHazard/RotorHazard/assets/23621888/f887d801-68b0-4f25-a76d-b29ed4015423)

**Comment by ethomas997** [comment] 2024-02-02 08:38
Please post full log zip here

**Comment by szafranski** [comment] 2024-02-03 01:19
Same on newest beta. How can I obtain that log?

**Comment by szafranski** [comment] 2024-02-03 01:23
I think this is it: 
[logs.zip](https://github.com/RotorHazard/RotorHazard/files/14148722/logs.zip)

**Comment by szafranski** [comment] 2024-02-03 01:25
I have some VERY interesting info - this only shows when connected to NuclearHazard PCB...

**Comment by ethomas997** [comment] 2024-02-03 01:53
> I think this is it: [logs.zip](https://github.com/RotorHazard/RotorHazard/files/14148722/logs.zip)

That zip contains no files.  See here for generating logs zip file:  https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md#logging

**Comment by szafranski** [comment] 2024-02-04 01:47
That should be it - sorry, used wrong zip command
[logs.zip](https://github.com/RotorHazard/RotorHazard/files/14155130/logs.zip)

**Comment by szafranski** [comment] 2024-02-04 01:48
I don't get it everytime, but most times and only when NH PCB is used

**Comment by ethomas997** [comment] 2024-02-04 07:31
Please post the 'config.json' file that was in use when the error(s) happened.

(In general it's better if you generate a ".zip" file using the "Download Logs" button (in Settings | System) and post it because this gives us more information.)

**Comment by ethomas997** [comment] 2024-02-04 20:34
@szafranski  Please also post the output of "pip list".

I'm testing on the same hardware & software setup that I see in your logs and I am not able to reproduce those errors; this is my setup:

```
2024-02-04 15:02:09.282: __main__ [INFO] Release: 4.1.0-beta.1 / Server API: 43 / Latest Node API: 35
2024-02-04 15:02:09.283: __main__ [DEBUG] Program started at 1707076928179, time=2024-02-04 15:02:08.179
2024-02-04 15:02:09.283: RHUtils [INFO] Host machine: Raspberry Pi 5 Model B Rev 1.0
2024-02-04 15:02:09.302: RHUtils [INFO] Host OS: Debian GNU/Linux 12 (bookworm) 64-bit (Linux 6.1.0-rpi8-rpi-2712)
2024-02-04 15:02:09.302: RHUtils [INFO] Python version: 3.11.2
2024-02-04 15:02:09.360: RHUtils [INFO] S32_BPill board detected
```

**Comment by szafranski** [comment] 2024-02-11 00:58
I downloaded logs via server gui. Attached
[rh_logs_20240211_015551.zip](https://github.com/RotorHazard/RotorHazard/files/14230940/rh_logs_20240211_015551.zip)

**Comment by ethomas997** [comment] 2024-02-11 03:19
Thanks for posting the logs-zip file.  When using the Pi 5, this line should not be present in the boot-config file:
`dtoverlay=gpio-shutdown,gpio_pin=19,debounce=2500`

Your boot-config file seems rather messy, with multiple repeated items.  See the current Software Setup for the recommended modifications to the boot-config file.  I think the RH Install Manager should adhere to those modifications.  Let me know if you think any settings should be different from the ones specified in the Software Setup doc.

Please see if starting from the default version of the boot-config file and modifying it as specified in the Software Settings clears up the GPIO errors.

**Comment by szafranski** [comment] 2024-02-11 13:32
Ok, so:

1. removed line: dtoverlay=gpio-shutdown,gpio_pin=19,debounce=2500
resolved the issue
but in your doc you have: 

<img width="784" alt="image" src="https://github.com/RotorHazard/RotorHazard/assets/23621888/ea8c27c4-dd83-48f8-bd03-3aa4ff59118f">

I don't see the info that in case of Pi 5 it should not be applied

2. As for my config file:
it only has what it should but with [<pi_version>]
and it causes those commands to be only applied when given pi version is found

3. Do you see any "unnecessary" code in my config file?

Thanks!

**Comment by ethomas997** [comment] 2024-02-13 06:56
That's the old doc; see the current on the main branch:  https://github.com/RotorHazard/RotorHazard/blob/main/doc/Software%20Setup.md#3-apply-changes-to-the-boot-configtxt-file

In your config file you have several instances of the same line duplicated multiple times (for instance "dtparam=act_led_trigger=heartbeat", and several others).

Also, I think "dtparam=i2c_baudrate=75000" should be present for all versions of the Pi.

**Comment by szafranski** [comment] 2024-02-13 09:56
Ok, I surely used the code from the stable branch so that's explained, thank you.
As for multiple lines - I did some testing so that's probably why. Actually it doesn't change anything but thanks for pointing that out. 

As for dtparam=i2c_baudrate=75000 - as far as I know it was only needed on Pi 3. I never used this on Pi 4 or 5 (and many other people as well) and everything seems to work ok. Are you sure it is needed?

**Comment by ethomas997** [comment] 2024-02-14 03:50
As I understand it the "dtparam=i2c_baudrate=75000" setting will affect the speed of the I2C bus when using Arduino/I2C nodes, regardless of the type of Pi used.

**Comment by szafranski** [comment] 2024-02-14 13:08
But is that necessary to work? I tested this on pi 4 with Arduino nodes and it doesn't seems to make any difference.

**Comment by ethomas997** [comment] 2024-02-22 05:09
We'd have to research what the default value is to really know.  But I'd say that unless there's good reason for removing it, the line should be present.  I'm going to close this issue, but feel free to reopen or make a new one if needed.

**Closed by ethomas997** 2024-02-22 05:09 UTC
