### ISSUE TITLE
Error with LEDs rpi_ws281 library when python3 is being used 

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#484] opened 2021-01-18 06:53 UTC
I came across an error: when LEDs number is defined - so when those are "enabled" basically - when server is being booted using python3 command ("python3 server.py"), there is a RuntimeError. Testes on WSL and Banana Pi. Same results. 
I tried to performing an installation procrdure using python2.7 like "sudo python2.7 setup.py install" isntead of "python3". Same results when server is being booted with python3.

Photo:
![image](https://user-images.githubusercontent.com/23621888/104881662-fad69a00-5961-11eb-9c23-1125c06f8f09.png)

**Comment by szafranski** [comment] 2021-01-18 06:55
First link is here by mistake. Sry

**Comment by szafranski** [comment] 2021-01-19 16:11
Looks like it maybe Banana Pi and WSL issue - due to limited hardware support on a WS driver side. Have to be checked on any Raspberry Pi to be confirmed.

**Comment by HazardCreative** [comment] 2021-01-24 18:01
LED requires GPIO access, which requires `sudo`. This message appears when you try to run the LED library (via RH) without it. Is that what's happening here?

**Comment by szafranski** [comment] 2021-01-24 18:06
Tried with sudo. Same issues. I have to grab some Raspberry and check.

W dniu niedz., 24.01.2021 o 19:01 Hazard Creative <notifications@github.com>
napisał(a):

**Comment by HazardCreative** [comment] 2021-01-24 18:17
You may also need to upgrade the package. It changed from `neopixel.py` to `rpi_ws281x.py`. (RH will try to use either.)

**Comment by ethomas997** [comment] 2021-01-25 02:02
I tested with multiple setups but was unable to reproduce the described error.

One thing to keep in mind is that for Python v3 the packages usually need to be installed/reinstalled using the "pip3" command, but that's probably not the root problem here.

**Comment by szafranski** [comment] 2021-01-25 02:08
Thanks for time spent on this. I think it is Banana Pi issue. If I come up
with sth useful I will make a PR on the ws281x repo.
I remembered about pip3 etc.

Thanks!!

W dniu pon., 25.01.2021 o 03:03 E Thomas <notifications@github.com>
napisał(a):

**Comment by HazardCreative** [comment] 2021-02-09 17:33
Closing as issue appears to be related to 3rd party library.

**Closed by HazardCreative** 2021-02-09 17:33 UTC
