### ISSUE TITLE
Automatically save laps and restart heat during a long pause with no laps recorded

### ISSUE THREAD

**Issue by frizzle101101** [RotorHazard/RotorHazard#551] opened 2021-04-08 17:15 UTC
So i have a goal to add auto heat tracking to rotorhazard so that race management is as simple as starting the timer at the beginning of the day and leaving if to self record the heats with some algorithmic programimg that keeps track of the use of the start gate and gaps between packs and ppl still using the gate... I believe it is quite possible just needs some development time.

This idea comes from practice mode timing in live time, where you can just start it and it records time not smartly but u can see when there a gap in the timing...if only it culd seperate out each pack i culd get propper race data with doing nothing

This is useful and most appropriate for small groups that still want to do timing without micro managing each heat when ppl are just flying for fun, as long as ppl follow a start line approach where no one is plugging in while others are flying then packs/heats shld be trackable programiticly 

If this sounds like an idea to you i was wondering if someone culd help me figure out where to start, not super familiar with the code base

**Comment by HazardCreative** [comment] 2021-04-08 17:32
Duplicate of #368 ?

**Comment by frizzle101101** [comment] 2021-04-11 04:00
> "You should stop as soon as all pilots are done racing," and let's say we don't care much about:  "so that new passes like walking past the gate aren't recorded." and "A short lap often appears because a pilot crashed near the gate or missed it and circled back around. In both these situations, it's the last pass that is valid and not the first one." And we don't care about this because it's a practice race and non-consistant times don't matter to us.
Partly Quoted from #370 describes best the reason for the need for a programmatical algorithmic way to stop a heat and start the next to preserve the propper use case as designed by rotorhazard currently. My idea is to remove the need for an active race manager in these practice situations and get a better output rather than a list of times; where it's clear there was one long lap for battery change and the rest consistent from battery to battery...the pros don't crash much and it's easy to see it in the times, plus easy to model automation after lol.

The #368 is the best solution to provide a live-time like practice mode but my idea is one step beyond that, it is a more advanced feature that automates the current use of the timer in a way where we can tell how many heats we run at the end of the day without having to actively click start race. With the right race time and battery change time parameters, for example(it may take more than that), an algorithm can figure out when the gate is in use and when its not; differentiating between one heat to the next. Ideally "as long as ppl follow a start line approach where no one is plugging in while others are flying then packs/heats should be trackable programiticly" honestly this habit safer for everyone anyways especially with DJI and analog mixing when racing.

**Comment by HazardCreative** [comment] 2021-04-11 11:28
So this issue could be alternately described as "Automatically save laps and restart heat during a long pause with no laps recorded"?

**Comment by frizzle101101** [comment] 2021-04-11 13:15
I believe so yes.

**Comment by HazardCreative** [comment] 2021-04-11 20:34
Thanks for the clarification. I'll give this some further thought.

**Comment by frizzle101101** [comment] 2021-04-12 02:19
If u need help let me know, do u have a discord for dev?

**Comment by frizzle101101** [comment] 2021-05-12 04:05
![image](https://user-images.githubusercontent.com/11097522/117916683-98f5c380-b2b5-11eb-83d5-6039c48bf8e7.png)
here's an image that represents the need for the idea, if it helps ur visualisation needs

**Comment by HazardCreative** [comment] 2023-11-22 05:17
Feature is now available via plugin.
https://github.com/HazardCreative/RotorHazard-Idle-Race_Handler

**Closed by HazardCreative** 2023-11-22 05:17 UTC
Labels: enhancement

**Comment by frizzle101101** [comment] 2023-11-22 19:10
Awesome work, great solution will test it out at a whoop session
