### ISSUE TITLE
After time, the server response time becomes slow. From 10 heartbeats per second to 1

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#732] opened 2023-04-27 18:02 UTC
When the server has been powered on for a while (30 minutes to 10 hours) It goes from sending 10 heartbeats to 1 heartbeat pr second.

Setups I have tried on:
- Raspberry Pi 3B+, with 8 arduinos connected with SPI
- Raspberry Pi 3B+ with 4 arduinos connected with USB
They both run 4.0.0 Beta2, but the servers have had this bug for over a year so I do not believe it is a new bug. I really hoped this new version would fix it, but it has not.

In the beginning they both run completely fine, the python daemon / service is at 3-4 percent when I have a webpage open of the server and they send heartbeat 10 times a second, like clockwork. Nice response time on the webservice and everything works great. 

But after a while, and it does not matter if it is a clean install or a database with 16 racers from a full day of racing, the response time drops from 10 heartbeats to 1 heartbeats and the python deamon / service is below 1 percent.

I have tried to reboot the server when this happends, but in order to get back to 10 heartbeats per second, I have to shut it down, and start it again. Then after an hour or so it goes bad again.. 

Any ideas on what to try to pinpoint what is going on?

( I use both Google Chrome / Inspect / Network and a custom websocket application to monitor the output from the server and measure heartbeats..)

**Comment by HazardCreative** [comment] 2023-04-28 13:27
I left two Pi 3B+ on for roughly 20 hours and it did not reproduce—both servers are sending heartbeats on the tenth. 

What do you see for memory usage for the RH server?

Because you have to shut down the system instead of restarting the server to restore performance, I wonder if something is going on outside RH. Is something else on the pi taking up a lot of CPU or memory?

We should try to determine what other differences there are between your system and mine. Do you use the desktop? (My Pis are both installed with Lite / no desktop) How have you set it up?

**Comment by fireduckfpv** [comment] 2023-04-28 13:37
I use the standard Rasbian OS with no desktop. It is a clean install and I can see nothing else taking up any CPU.

![image](https://user-images.githubusercontent.com/24962379/235162218-9cd1aa1f-bc17-42ae-84de-17c24185508f.png)

**Comment by fireduckfpv** [comment] 2023-04-28 13:38
I am thinking that it might be an arduino issue, I am going to try to disconnect some of the arduinos and do some testing again.

**Comment by fireduckfpv** [comment] 2023-04-28 13:39
The odd thing is that the CPU useage actually goes down when it goes to 1 heartbeat pr second..

**Comment by HazardCreative** [comment] 2023-04-28 13:47
> I am thinking that it might be an arduino issue

Yes, that is definitely the next place to explore. The Pi that I left with the RH server running was STM32-based. Because your comments suggested the issue might be outside the server, I ran the second pi with no RH server running and just started it up to check the heartbeat.

I have already begin a new test with the server running on the Pi with Arduinos. If this replicates the issue.

The lower CPU load of the RH server does support the theory that the Arduinos are slowing down. We will see what my next test returns.

**Comment by HazardCreative** [comment] 2023-04-29 17:58
My Pi3B+ with 4 Arduinos is still going with no noticeable slowdown after just over 24hrs.

**Comment by fireduckfpv** [comment] 2023-05-01 16:23
I am currently testing with 8 active sensors and now there is no slowdown..  Maybe this is only an issue when one or more sensors are disabled..  I will do more testing.

**Comment by HazardCreative** [comment] 2023-05-01 16:58
Thanks for continuing to test. Let us know if you can isolate this.

**Comment by fireduckfpv** [comment] 2023-05-01 21:52
Finally caught it happen! :)

This time it was with 8 arduino sensors, 4 of them disabled. I will continue to try to make this happen with 8 enabled sensors.

Here is the database right after it happened.
[database_20230501_224700.zip](https://github.com/RotorHazard/RotorHazard/files/11368237/database_20230501_224700.zip)

Here is the server log as it happened! 
Up to 22:39 (I think) it is 10hb pr second, after it still works but is only 1 hb pr second and the web response time is up to several seconds.


2023-05-01 19:13:47.327: __main__ [INFO] Staging new race, format: Fastest 3 Laps Qualifier
2023-05-01 19:13:47.332: __main__ [INFO] Racing heat 'Heat 1' round 2, pilots: Archaeopteryx, Bond1, Zenta, fireduck
2023-05-01 19:13:47.451: __main__ [INFO] Forcing race format from class setting: 'Fastest 3 Laps Qualifier' (7)
2023-05-01 19:13:47.474: __main__ [INFO] Current laps cleared
2023-05-01 19:13:47.562: __main__ [INFO] Lowering EnterAt/ExitAt values at start of race, amount=10%, duration=30 secs
2023-05-01 19:13:47.563: __main__ [INFO] For node 1 lowering EnterAt from 109 to 108 and ExitAt from 96 to 95
2023-05-01 19:13:47.683: __main__ [INFO] Not lowering EnterAt/ExitAt values for node 2 because EnterAt value (98) unchanged
2023-05-01 19:13:47.684: __main__ [INFO] For node 3 lowering EnterAt from 88 to 87 and ExitAt from 72 to 71
2023-05-01 19:13:47.748: __main__ [INFO] For node 4 lowering EnterAt from 90 to 89 and ExitAt from 74 to 73
2023-05-01 19:13:51.459: __main__ [INFO] Race started at 4629.127 (1682964831457)
2023-05-01 19:13:52.687: __main__ [INFO] Simulated lap: Node 1
2023-05-01 19:13:53.026: RHInterface [INFO] For node 1 restoring EnterAt to 109 and ExitAt to 96
2023-05-01 19:13:53.276: __main__ [INFO] Simulated lap: Node 2
2023-05-01 19:13:53.805: __main__ [INFO] Simulated lap: Node 3
2023-05-01 19:13:53.957: RHInterface [INFO] For node 3 restoring EnterAt to 88 and ExitAt to 72
2023-05-01 19:13:54.742: __main__ [INFO] Simulated lap: Node 4
2023-05-01 19:13:54.984: RHInterface [INFO] For node 4 restoring EnterAt to 90 and ExitAt to 74
2023-05-01 19:13:58.013: __main__ [INFO] Simulated lap: Node 1
2023-05-01 19:13:59.550: __main__ [INFO] Simulated lap: Node 2
2023-05-01 19:14:00.084: __main__ [INFO] Simulated lap: Node 3
2023-05-01 19:14:00.998: __main__ [INFO] Simulated lap: Node 4
2023-05-01 19:14:20.644: __main__ [INFO] Race stopped at 4658.313 (1682964860644), duration 29s
2023-05-01 19:14:21.785: __main__ [INFO] Current laps cleared
2023-05-01 19:14:53.988: __main__ [INFO] Race times adjusted for: Heat 2 Round 1 / Bond1
2023-05-01 19:14:54.112: __main__ [INFO] Updated calibration with best discovered values
2023-05-01 19:14:54.292: RHData [INFO] Building Class 1 results
2023-05-01 19:14:54.553: PageCache [INFO] T4692: Built results data in: 0.155529s
2023-05-01 19:14:57.780: __main__ [INFO] Race times adjusted for: Heat 2 Round 1 / Bond1
2023-05-01 19:14:57.930: __main__ [INFO] Updated calibration with best discovered values
2023-05-01 19:14:58.224: RHData [INFO] Building Class 1 results
2023-05-01 19:14:58.681: PageCache [INFO] T4696: Built results data in: 0.285885s
2023-05-01 19:25:17.130: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 19:38:02.616: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 20:12:41.462: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 21:17:20.490: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 21:32:33.514: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 22:33:38.775: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 22:34:25.215: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 121] Remote I/O error
2023-05-01 22:39:49.441: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:50.481: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:50.482: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=14 size=8 retry=2 ts=16988.150980306
2023-05-01 22:39:51.521: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:51.522: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=14 size=8 retry=3 ts=16989.190898216
2023-05-01 22:39:52.561: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:52.562: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=14 size=8 retry=4 ts=16990.230967688
2023-05-01 22:39:53.601: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:53.602: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=10 cmd=14 size=8 retry=5 ts=16991.270955806
2023-05-01 22:39:53.602: RHInterface [ERROR] Exception in RHInterface update_loop():
Traceback (most recent call last):
  File "../interface/RHInterface.py", line 211, in update_loop
    self.update()
  File "../interface/RHInterface.py", line 232, in update
    data.extend(node.read_block(self, READ_LAP_EXTREMUMS, 8))
TypeError: 'NoneType' object is not iterable
2023-05-01 22:39:55.681: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:56.721: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:56.722: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=2 ts=16994.390972247
2023-05-01 22:39:57.761: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:57.762: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=3 ts=16995.430924482
2023-05-01 22:39:58.801: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:58.802: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=4 ts=16996.471002237
2023-05-01 22:39:59.841: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:39:59.842: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=8 cmd=13 size=8 retry=5 ts=16997.510913588
2023-05-01 22:40:00.881: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:01.921: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:01.922: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=2 ts=16999.590976393
2023-05-01 22:40:02.961: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:02.962: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=3 ts=17000.630993786
2023-05-01 22:40:04.001: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:04.002: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=4 ts=17001.670944096
2023-05-01 22:40:05.041: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:05.042: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=10 cmd=13 size=8 retry=5 ts=17002.711052062
2023-05-01 22:40:10.321: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:10.322: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=12 cmd=13 size=8 retry=5 ts=17007.990926384
2023-05-01 22:40:11.441: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:12.481: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:12.482: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=14 cmd=13 size=8 retry=2 ts=17010.15098368
2023-05-01 22:40:13.521: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:13.522: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=14 cmd=13 size=8 retry=3 ts=17011.190966754
2023-05-01 22:40:14.561: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:14.562: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=14 cmd=13 size=8 retry=4 ts=17012.230969256
2023-05-01 22:40:15.601: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:15.602: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=14 cmd=13 size=8 retry=5 ts=17013.27097306
2023-05-01 22:40:16.721: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:17.761: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:17.762: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=2 ts=17015.430974058
2023-05-01 22:40:18.801: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:18.802: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=3 ts=17016.470976301
2023-05-01 22:40:19.841: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:19.842: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=8 cmd=13 size=8 retry=4 ts=17017.511437239
2023-05-01 22:40:20.881: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:20.882: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=8 cmd=13 size=8 retry=5 ts=17018.551032089
2023-05-01 22:40:21.921: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:22.961: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:22.962: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=2 ts=17020.631039441
2023-05-01 22:40:24.001: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:24.002: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=3 ts=17021.670969238
2023-05-01 22:40:25.041: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:25.042: BaseHardwareInterface [INFO] Interface: Retry (IOError) in read_block:  addr=10 cmd=13 size=8 retry=4 ts=17022.710985753
2023-05-01 22:40:26.081: BaseHardwareInterface [INFO] Interface: Read Error: [Errno 110] Connection timed out
2023-05-01 22:40:26.082: BaseHardwareInterface [INFO] Interface: Retry (IOError) limit reached in read_block:  addr=10 cmd=13 size=8 retry=5 ts=17023.750984665

**Comment by fireduckfpv** [comment] 2023-05-02 17:20
Just FYI, I still have not been able to reproduce the error when all sensors are enabled... Still trying though..

**Comment by ethomas997** [comment] 2023-06-29 09:10
Looks like this was a hardware problem, so closing this issue.  @fireduckfpv feel free to reopen if needed.

**Closed by ethomas997** 2023-06-29 09:10 UTC
