### ISSUE TITLE
Pilot 1 missing 

### ISSUE THREAD

**Issue by targetdozer** [RotorHazard/RotorHazard#43] opened 2019-02-09 23:44 UTC
On page "current", voice calls, pilot one is not available
![screenshot_2019-02-10-00-24-05_kindlephoto-49867241](https://user-images.githubusercontent.com/37815020/52527781-6e7bc100-2cce-11e9-9eaa-defe1735e860.png)
![screenshot_2019-02-10-00-23-48_kindlephoto-49945932](https://user-images.githubusercontent.com/37815020/52527783-750a3880-2cce-11e9-82e0-03a0a6d412e2.png)

**Comment by HazardCreative** [comment] 2019-02-11 13:47
Thanks for your feedback! We've actually found and fixed this one already in the development code, so it'll be taken care of in the next release.

Duplicate of #21

**Closed by HazardCreative** 2019-02-11 13:47 UTC
